#!/bin/bash

# System Variables
user=$(whoami)
hostname=$(hostname | sed 's/.local//g')
distro="OS X $(sw_vers -productVersion)"
kernel=$(uname)
uptime=$(uptime | sed 's/.*up \([^,]*\), .*/\1/')
shell="$SHELL"
terminal="$TERM"
#brewpackages="`brew list -l | wc -l | awk '{print $1 }'`"
macportpackages="`port installed | wc -l | awk '{print $1 }'`"
cpu=$(sysctl -n machdep.cpu.brand_string)
mem=$(sysctl -n hw.memsize)
ram="$((mem/1000000000)) GB"
disk=`df | head -2 | tail -1 | awk '{print $5}'`

# Colors Variables
red="1"
green="2"
yellow="3"
blue="4"
purple="5"
lightblue="6"
grey="7"

textColor=$(tput setaf $lightblue)
normal=$(tput sgr0)

# Package Manager (Homebrew or Macports)
packagehandler=$macportpackages

# Add a -c option to enable classic color logo
if [[ $1 == "-c" ]] || [[ $1 == "--color" ]]; then
  GREEN='\033[00;32m'
  YELLOW='\033[00;33m'
  LRED='\033[01;31m'
  RED='\033[00;31m'
  PURPLE='\033[00;35m'
  CYAN='\033[00;36m'
  BLUE='\033[00;34m'
fi

# create colored text variables
userText="${textColor}User:${normal}"
hostnameText="${textColor}Hostname:${normal}"
distroText="${textColor}Distro:${normal}"
kernelText="${textColor}Kernel:${normal}"
uptimeText="${textColor}Uptime:${normal}"
shellText="${textColor}Shell:${normal}"
terminalText="${textColor}Hostname:${normal}"
packagehandlerText="${textColor}Packages:${normal}"
cpuText="${textColor}CPU:${normal}"
memoryText="${textColor}Memory:${normal}"
diskText="${textColor}Disk:${normal}"

echo -e "
                  
${GREEN}                  ###
${GREEN}                ####	              $userText $user
${GREEN}                ###                   $hostnameText $hostname
${GREEN}       ####### ##  #######            $distroText $distro
${YELLOW}     ######################           $kernelText $kernel
${YELLOW}    #####################             $uptimeText $uptime
${LRED}    ####################              $shellText $shell
${RED}    ####################              $terminalText $terminal
${RED}    #####################             $packagehandlerText $packagehandler
${PURPLE}     ######################           $cpuText $cpu
${PURPLE}      ####################	      $memoryText $ram
${BLUE}        ################              $diskText $disk
${BLUE}         ####     ##### ${normal}
               
"