#!/bin/bash

# Variables
user=$(whoami)
hostname=$(hostname | sed 's/.local//g')
distro="OS X $(sw_vers -productVersion)"
kernel=$(uname)
uptime=$(uptime | sed 's/.*up \([^,]*\), .*/\1/')
shell="$SHELL"
terminal="$TERM"
#brewpackages="`brew list -l | wc -l | awk '{print $1 }'`"
macportpackages="`port installed | wc -l | awk '{print $1 }'`"
cpu=$(sysctl -n machdep.cpu.brand_string)
mem=$(sysctl -n hw.memsize)
ram="$((mem/1000000000)) GB"
disk=`df | head -2 | tail -1 | awk '{print $5}'`

# Colors
red="1"
green="2"
yellow="3"
blue="4"
purple="5"
lightblue="6"
grey="7"

color=$(tput setaf $lightblue)
normal=$(tput sgr0)

packagehandler=$macportpackages

userText="${color}User:${normal}"
hostnameText="${color}Hostname:${normal}"
distroText="${color}Distro:${normal}"
kernelText="${color}Kernel:${normal}"
uptimeText="${color}Uptime:${normal}"
shellText="${color}Shell:${normal}"
terminalText="${color}Hostname:${normal}"
packagehandlerText="${color}Packages:${normal}"
cpuText="${color}CPU:${normal}"
memoryText="${color}Memory:${normal}"
diskText="${color}Disk:${normal}"

echo "

                  ###
                ####                  $userText $user
                ###                   $hostnameText $hostname
       ########    #######            $distroText $distro
     ######################           $kernelText $kernel
    #####################             $uptimeText $uptime
    ####################              $shellText $shell
    ####################              $terminalText $terminal
    #####################             $packagehandlerText $packagehandler
     ######################           $cpuText $cpu
      ####################            $memoryText $ram
        ################              $diskText $disk
         ####     #####

"
